apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app: vault
data:
  config.hcl: |
    storage "postgresql" {
      connection_url = "{{ .Values.vault.config.postgresql.connection_url }}"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
