apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: {{ .Values.vault.image }}
          args:
            - "server"
          env:
            - name: VAULT_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: config.hcl
          ports:
            - containerPort: {{ .Values.vault.service.port }}
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
