apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: hashicorp
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: {{ .Values.vault.service.port }}
      targetPort: 8200
  type: {{ .Values.vault.service.type }}
