apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
    - port: {{ .Values.vault.service.port }}
      targetPort: 8200
  type: {{ .Values.vault.service.type }}
