apiVersion: v1
kind: Pod
metadata:
  name: test-connection
  labels:
    app: test
spec:
  containers:
    - name: test-vault
      image: busybox
      command: ['sh', '-c', 'nc -zv vault {{ .Values.vault.service.port }}']
    - name: test-postgres
      image: busybox
      command: ['sh', '-c', 'nc -zv postgres {{ .Values.postgres.service.port }}']
  restartPolicy: Never
