apiVersion: v1
kind: Pod
metadata:
  name: "test-connection"
  namespace: hashicorp
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['vault:{{ .Values.vault.service.port }}']
  restartPolicy: Never
