vault:
  image: "hashicorp/vault:latest"
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer  # Ensure correct type
    port: 8200  # Define port properly
  config:
    storage: "postgres"
    postgresql:
      connection_url: "postgresql://vault:vaultpassword@postgres:5432"

postgres:
  image: "postgres:latest"
  replicas: 1
  service:
    type: ClusterIP
    port: 5432  # Define port properly
  storage:
    size: 1Gi
