vault:
  image: "hashicorp/vault:latest"
  replicas: 1
  service:
    enabled: true
    type: ClusterIP
    port: 8200

  config:
    storage: "postgres"
    postgresql:
      connection_url: "postgresql://vault:vaultpassword@postgres:5432"  # Fixed missing quote

postgres:
  image: "postgres:latest"
  replicas: 1
  service:
    type: ClusterIP
    port: 5432
  storage:
    size: 1Gi

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
